// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ids/ids.proto

package ids

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceIp      string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatEvent) Reset() {
	*x = ThreatEvent{}
	mi := &file_proto_ids_ids_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatEvent) ProtoMessage() {}

func (x *ThreatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ids_ids_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatEvent.ProtoReflect.Descriptor instead.
func (*ThreatEvent) Descriptor() ([]byte, []int) {
	return file_proto_ids_ids_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *ThreatEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ThreatEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ThreatEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type BlockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceIp      string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCommand) Reset() {
	*x = BlockCommand{}
	mi := &file_proto_ids_ids_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommand) ProtoMessage() {}

func (x *BlockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ids_ids_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommand.ProtoReflect.Descriptor instead.
func (*BlockCommand) Descriptor() ([]byte, []int) {
	return file_proto_ids_ids_proto_rawDescGZIP(), []int{1}
}

func (x *BlockCommand) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *BlockCommand) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

var File_proto_ids_ids_proto protoreflect.FileDescriptor

const file_proto_ids_ids_proto_rawDesc = "" +
	"\n" +
	"\x13proto/ids/ids.proto\x12\x03ids\"u\n" +
	"\vThreatEvent\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"H\n" +
	"\fBlockCommand\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12\x1b\n" +
	"\tissued_at\x18\x02 \x01(\x03R\bissuedAt2E\n" +
	"\n" +
	"IDSService\x127\n" +
	"\fReportThreat\x12\x10.ids.ThreatEvent\x1a\x11.ids.BlockCommand(\x010\x01B0Z.github.com/sanjay-rajjan/network-ids/proto/idsb\x06proto3"

var (
	file_proto_ids_ids_proto_rawDescOnce sync.Once
	file_proto_ids_ids_proto_rawDescData []byte
)

func file_proto_ids_ids_proto_rawDescGZIP() []byte {
	file_proto_ids_ids_proto_rawDescOnce.Do(func() {
		file_proto_ids_ids_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ids_ids_proto_rawDesc), len(file_proto_ids_ids_proto_rawDesc)))
	})
	return file_proto_ids_ids_proto_rawDescData
}

var file_proto_ids_ids_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ids_ids_proto_goTypes = []any{
	(*ThreatEvent)(nil),  // 0: ids.ThreatEvent
	(*BlockCommand)(nil), // 1: ids.BlockCommand
}
var file_proto_ids_ids_proto_depIdxs = []int32{
	0, // 0: ids.IDSService.ReportThreat:input_type -> ids.ThreatEvent
	1, // 1: ids.IDSService.ReportThreat:output_type -> ids.BlockCommand
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ids_ids_proto_init() }
func file_proto_ids_ids_proto_init() {
	if File_proto_ids_ids_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ids_ids_proto_rawDesc), len(file_proto_ids_ids_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ids_ids_proto_goTypes,
		DependencyIndexes: file_proto_ids_ids_proto_depIdxs,
		MessageInfos:      file_proto_ids_ids_proto_msgTypes,
	}.Build()
	File_proto_ids_ids_proto = out.File
	file_proto_ids_ids_proto_goTypes = nil
	file_proto_ids_ids_proto_depIdxs = nil
}
