// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/ids/ids.proto

package ids

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IDSService_ReportThreat_FullMethodName = "/ids.IDSService/ReportThreat"
)

// IDSServiceClient is the client API for IDSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDSServiceClient interface {
	ReportThreat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ThreatEvent, BlockCommand], error)
}

type iDSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIDSServiceClient(cc grpc.ClientConnInterface) IDSServiceClient {
	return &iDSServiceClient{cc}
}

func (c *iDSServiceClient) ReportThreat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ThreatEvent, BlockCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IDSService_ServiceDesc.Streams[0], IDSService_ReportThreat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ThreatEvent, BlockCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IDSService_ReportThreatClient = grpc.BidiStreamingClient[ThreatEvent, BlockCommand]

// IDSServiceServer is the server API for IDSService service.
// All implementations must embed UnimplementedIDSServiceServer
// for forward compatibility.
type IDSServiceServer interface {
	ReportThreat(grpc.BidiStreamingServer[ThreatEvent, BlockCommand]) error
	mustEmbedUnimplementedIDSServiceServer()
}

// UnimplementedIDSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIDSServiceServer struct{}

func (UnimplementedIDSServiceServer) ReportThreat(grpc.BidiStreamingServer[ThreatEvent, BlockCommand]) error {
	return status.Error(codes.Unimplemented, "method ReportThreat not implemented")
}
func (UnimplementedIDSServiceServer) mustEmbedUnimplementedIDSServiceServer() {}
func (UnimplementedIDSServiceServer) testEmbeddedByValue()                    {}

// UnsafeIDSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDSServiceServer will
// result in compilation errors.
type UnsafeIDSServiceServer interface {
	mustEmbedUnimplementedIDSServiceServer()
}

func RegisterIDSServiceServer(s grpc.ServiceRegistrar, srv IDSServiceServer) {
	// If the following call panics, it indicates UnimplementedIDSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IDSService_ServiceDesc, srv)
}

func _IDSService_ReportThreat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IDSServiceServer).ReportThreat(&grpc.GenericServerStream[ThreatEvent, BlockCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IDSService_ReportThreatServer = grpc.BidiStreamingServer[ThreatEvent, BlockCommand]

// IDSService_ServiceDesc is the grpc.ServiceDesc for IDSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ids.IDSService",
	HandlerType: (*IDSServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportThreat",
			Handler:       _IDSService_ReportThreat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ids/ids.proto",
}
