FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o coordinator ./coordinator/

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/coordinator .

EXPOSE 50051
EXPOSE 9090

CMD ["./coordinator"]

