global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'coordinator'
    static_configs:
      - targets: ['coordinator:9090']

  - job_name: 'agent-node-1'
    static_configs:
      - targets: ['100.26.97.92:9091']

  - job_name: 'agent-node-2'
    static_configs:
      - targets: ['54.145.136.6:9091']